language: go
go: master
env:
- VERSION=$(cat VERSION)
before_deploy:
- "GO111MODULE=on GOOS=linux  GOARCH=amd64 go build -o txt2Htxt-v$VERSION-linux-amd64"
- "GO111MODULE=on GOOS=darwin GOARCH=amd64 go build -o txt2Htxt-v$VERSION-darwin-amd64"
- "GO111MODULE=on GOOS=windows GOARCH=amd64 go build -o txt2Htxt-v$VERSION-windows-amd64.exe"
notifications:
  email:
  - licoolgo@gmail.com
deploy:
  provider: releases
  api_key:
    secure: DtK7RCe4IE7mmKVe0HTvpxymbPtgPTuGJkEe+YO0eBdbOSpogB+LgPDuw5oaPGEfpkGvo+IKFpdMQQ42NvfIu8GcShZNQf7eskLdHqnUBnHvkLwaLZ7XrBq8sWszmlrqTV0LxGgOzVDv7+EBIGrz0qqsi8KUa/VmR1Sr2etOy+sb8d7L5Hfrck4KxvutQVqcyYAQvuc6xI4fCEml9GK/Sp/YJ0nDGrhU99rwLVcEFSfYhg3GukjZfAU89OCm0MmP/fTQmnhbCLXWb53clQY0dEYEDOYqDnw9Xag9iTY0D3Pg5L+1AT+5h9pitDsyZiahAgY7t0Qf8R0Aqgcylp44wyabPiphbLVmKGxa1Ak9irgU90LwwL7sRlCqR9zJvW1o+wub7EwAD8uTLH/hzM5XBsmntn/sqRoE1SKpK9fzu+gv7cszaJoYVz5NRMRLY+K8FDQnlz5i/VWP1YeZCXrZtQhszK5/Hco8eeHZ2GM69mimZ/R7p8deOLQbW3uEUgrN3jIbz8aDefeLcbbA/XgRJI4gC0c8J0kjERSLh+M9vGtC6M9u9gfInYEkf15PxM//mWnh5tcJ2LkyLWTBiUaod5ddEQrchBVDLnAR2ROAApNg4vR8vqfrma6J5FGYPdefITPmvtqfT4Ls2q5KRhfu+hBjlKzXWSqvaALMbL+2u/M=
  file:
  - "txt2Htxt-v$VERSION-linux-amd64"
  - "txt2Htxt-v$VERSION-darwin-amd64"
  - "txt2Htxt-v$VERSION-windows-amd64.exe"
  skip_cleanup: true
  on:
    tags: true